In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import arff

In [4]:
data, meta = arff.loadarff(r"data/3year.arff")
df = pd.DataFrame(data)
df.head()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.174190,0.41299,0.14371,1.3480,-28.9820,0.60383,0.219460,1.1225,1.1961,0.46359,...,0.163960,0.375740,0.83604,0.000007,9.7145,6.2813,84.291,4.3303,4.0341,b'0'
1,0.146240,0.46038,0.28230,1.6294,2.5952,0.00000,0.171850,1.1721,1.6018,0.53962,...,0.027516,0.271000,0.90108,0.000000,5.9882,4.1103,102.190,3.5716,5.9500,b'0'
2,0.000595,0.22612,0.48839,3.1599,84.8740,0.19114,0.004572,2.9881,1.0077,0.67566,...,0.007639,0.000881,0.99236,0.000000,6.7742,3.7922,64.846,5.6287,4.4581,b'0'
3,0.024526,0.43236,0.27546,1.7833,-10.1050,0.56944,0.024526,1.3057,1.0509,0.56453,...,0.048398,0.043445,0.95160,0.142980,4.2286,5.0528,98.783,3.6950,3.4844,b'0'
4,0.188290,0.41504,0.34231,1.9279,-58.2740,0.00000,0.233580,1.4094,1.3393,0.58496,...,0.176480,0.321880,0.82635,0.073039,2.5912,7.0756,100.540,3.6303,4.6375,b'0'

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10503 entries, 0 to 10502
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Attr1   10503 non-null  float64
 1   Attr2   10503 non-null  float64
 2   Attr3   10503 non-null  float64
 3   Attr4   10485 non-null  float64
 4   Attr5   10478 non-null  float64
 5   Attr6   10503 non-null  float64
 6   Attr7   10503 non-null  float64
 7   Attr8   10489 non-null  float64
 8   Attr9   10500 non-null  float64
 9   Attr10  10503 non-null  float64
 10  Attr11  10503 non-null  float64
 11  Attr12  10485 non-null  float64
 12  Attr13  10460 non-null  float64
 13  Attr14  10503 non-null  float64
 14  Attr15  10495 non-null  float64
 15  Attr16  10489 non-null  float64
 16  Attr17  10489 non-null  float64
 17  Attr18  10503 non-null  float64
 18  Attr19  10460 non-null  float64
 19  Attr20  10460 non-null  float64
 20  Attr21  9696 non-null   float64
 21  Attr22  10503 non-null  float64
 22  Attr23  10460 non-null  float64
 23  Attr24  10276 non-null  float64
 24  Attr25  10503 non-null  float64
 25  Attr26  10489 non-null  float64
 26  Attr27  9788 non-null   float64
 27  Attr28  10275 non-null  float64
 28  Attr29  10503 non-null  float64
 29  Attr30  10460 non-null  float64
 30  Attr31  10460 non-null  float64
 31  Attr32  10402 non-null  float64
 32  Attr33  10485 non-null  float64
 33  Attr34  10489 non-null  float64
 34  Attr35  10503 non-null  float64
 35  Attr36  10503 non-null  float64
 36  Attr37  5767 non-null   float64
 37  Attr38  10503 non-null  float64
 38  Attr39  10460 non-null  float64
 39  Attr40  10485 non-null  float64
 40  Attr41  10301 non-null  float64
 41  Attr42  10460 non-null  float64
 42  Attr43  10460 non-null  float64
 43  Attr44  10460 non-null  float64
 44  Attr45  9912 non-null   float64
 45  Attr46  10485 non-null  float64
 46  Attr47  10417 non-null  float64
 47  Attr48  10503 non-null  float64
 48  Attr49  10460 non-null  float64
 49  Attr50  10489 non-null  float64
 50  Attr51  10503 non-null  float64
 51  Attr52  10417 non-null  float64
 52  Attr53  10275 non-null  float64
 53  Attr54  10275 non-null  float64
 54  Attr55  10503 non-null  float64
 55  Attr56  10460 non-null  float64
 56  Attr57  10503 non-null  float64
 57  Attr58  10474 non-null  float64
 58  Attr59  10503 non-null  float64
 59  Attr60  9911 non-null   float64
 60  Attr61  10486 non-null  float64
 61  Attr62  10460 non-null  float64
 62  Attr63  10485 non-null  float64
 63  Attr64  10275 non-null  float64
 64  class   10503 non-null  object
dtypes: float64(64), object(1)
memory usage: 5.2+ MB

In [36]:
print(f"number of numeric features is {len(df.select_dtypes("number").columns)}")

number of numeric features is 64

In [14]:
df.describe()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64
count,10503.000000,10503.000000,10503.000000,10485.000000,1.047800e+04,10503.000000,10503.000000,10489.000000,10500.000000,10503.000000,...,1.050300e+04,10460.000000,10503.000000,10474.000000,10503.000000,9.911000e+03,10486.000000,1.046000e+04,10485.000000,10275.000000
mean,0.052844,0.619911,0.095490,9.980499,-1.347662e+03,-0.121159,0.065624,19.140113,1.819254,0.366093,...,6.638549e+03,-0.530082,-0.014817,3.848794,1.429319,5.713363e+02,13.935361,1.355370e+02,9.095149,35.766800
std,0.647797,6.427041,6.420056,523.691951,1.185806e+05,6.970625,0.651152,717.756745,7.581659,6.428603,...,5.989196e+04,55.978608,18.684047,190.201224,77.273270,3.715967e+04,83.704103,2.599116e+04,31.419096,428.298315
min,-17.692000,0.000000,-479.730000,0.002080,-1.190300e+07,-508.120000,-17.692000,-2.081800,-1.215700,-479.730000,...,-7.513800e+05,-5691.700000,-1667.300000,-198.690000,-172.070000,0.000000e+00,-6.590300,-2.336500e+06,-0.000156,-0.000102
25%,0.000686,0.253955,0.017461,1.040100,-5.207075e+01,0.000000,0.002118,0.431270,1.011275,0.297340,...,1.462100e+01,0.005137,0.006796,0.875560,0.000000,5.533150e+00,4.486075,4.073700e+01,3.062800,2.023350
50%,0.043034,0.464140,0.198560,1.605600,1.579300e+00,0.000000,0.050945,1.111000,1.199000,0.515500,...,8.822900e+02,0.051765,0.106880,0.953060,0.002976,9.952100e+00,6.677300,7.066400e+01,5.139200,4.059300
75%,0.123805,0.689330,0.419545,2.959500,5.608400e+01,0.072584,0.142275,2.857100,2.059100,0.725635,...,4.348900e+03,0.130010,0.271310,0.995927,0.240320,2.093600e+01,10.587500,1.182200e+02,8.882600,9.682750
max,52.652000,480.730000,17.708000,53433.000000,6.854400e+05,45.533000,52.652000,53432.000000,740.440000,11.837000,...,3.380500e+06,293.150000,552.640000,18118.000000,7617.300000,3.660200e+06,4470.400000,1.073500e+06,1974.500000,21499.000000

In [5]:
df.isna().sum()

Attr1       0
Attr2       0
Attr3       0
Attr4      18
Attr5      25
         ...
Attr61     17
Attr62     43
Attr63     18
Attr64    228
class       0
Length: 65, dtype: int64

In [10]:
cols_with_missing_values = df.columns[df.isna().sum() > 0]
len(cols_with_missing_values)

44

5% or less of total values
The amount of missing data is so small that a simple mean/median imputation won't bias the model much.

In [12]:
threshold_na = len(df) * 0.05
cols_to_imp = df.columns[(df.isna().sum() <= threshold_na) & (df.isna().sum()>0)]
len(cols_to_imp)

39

In [43]:
df[cols_to_imp].fillna("median")

,Attr4,Attr5,Attr8,Attr9,Attr12,Attr13,Attr15,Attr16,Attr17,Attr19,...,Attr50,Attr52,Attr53,Attr54,Attr56,Attr58,Attr61,Attr62,Attr63,Attr64
0,1.348,-28.982,1.1225,1.1961,0.53139,0.14233,592.24,0.6163,2.4213,0.12272,...,1.348,0.27622,1.0457,1.0458,0.16396,0.83604,6.2813,84.291,4.3303,4.0341
1,1.6294,2.5952,1.1721,1.6018,0.38317,0.12647,829.46,0.44004,2.1721,0.10728,...,1.5874,0.28791,2.0044,2.0044,0.027516,0.90108,4.1103,102.19,3.5716,5.95
2,3.1599,84.874,2.9881,1.0077,0.020219,0.030966,2094.1,0.1743,4.4225,0.003592,...,3.1599,0.17903,2.3667,2.3667,0.007639,0.99236,3.7922,64.846,5.6287,4.4581
3,1.7833,-10.105,1.3057,1.0509,0.069747,0.036812,3299.4,0.11063,2.3129,0.018876,...,1.4504,0.2844,1.5139,1.7303,0.048398,0.9516,5.0528,98.783,3.695,3.4844
4,1.9279,-58.274,1.4094,1.3393,0.63317,0.1878,602.31,0.606,2.4094,0.17441,...,1.7136,0.33449,2.0256,2.1735,0.17648,0.82635,7.0756,100.54,3.6303,4.6375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10498,0.51658,-31.866,0.61855,1.012,0.006178,0.018378,2879.3,0.12677,1.7222,0.000714,...,0.41198,0.11701,0.47211,0.62666,0.011834,0.98817,39.15,42.202,8.6489,5.2646
10499,2.1698,12.748,0.66983,0.94694,-0.27316,0.020928,6875.9,0.053084,1.8098,-0.024518,...,0.49398,0.084993,0.50905,1.096,-0.056037,1.056,9.2851,32.761,11.141,1.9276
10500,0.46526,-145.31,0.19113,1.0999,-0.20616,-0.11988,-2324.0,-0.15706,1.1911,-0.11988,...,0.35444,0.49816,0.22843,0.41442,0.14412,0.85427,9.6966,212.23,1.7198,1.5659
10501,1.523,-10.158,0.9899,1.0123,0.015392,0.01447,6789.0,0.053763,1.9989,0.004143,...,1.523,0.27247,2.08,2.08,0.012186,0.98781,4.3536,98.24,3.7154,7.8068
10502,1.0045,-50.221,0.055122,2.1268,0.003119,0.011297,14398.0,0.02535,1.0551,0.001206,...,0.87175,0.39589,0.30031,1.0206,0.023492,0.97208,3.996,141.16,2.5857,12.225